docRoot                   $VH_ROOT/public_html
vhDomain                  $VH_NAME
vhAliases                 www.$VH_NAME
adminEmails               support@ninesys19.com
enableGzip                1
enableIpGeo               1

index  {
  useServer               0
  indexFiles              index.php, index.html
}

errorlog $VH_ROOT/logs/$VH_NAME.error_log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
}

accesslog $VH_ROOT/logs/$VH_NAME.access_log {
  useServer               0
  logFormat               "%h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-Agent}i""
  logHeaders              5
  rollingSize             10M
  keepDays                10  
  compressArchive         1
}

scripthandler  {
  add                     lsapi:dtfni3272 php
}

extprocessor dtfni3272 {
  type                    lsapi
  address                 UDS://tmp/lshttpd/dtfni3272.sock
  maxConns                10
  env                     LSAPI_CHILDREN=10
  initTimeout             600
  retryTimeout            0
  persistConn             1
  pcKeepAliveTimeout      1
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/lsphp83/bin/lsphp
  extUser                 dtfni3272
  extGroup                dtfni3272
  memSoftLimit            1024M
  memHardLimit            1024M
  procSoftLimit           400
  procHardLimit           500
}

extprocessor dtf-backend {
  type                    proxy
  address                 127.0.0.1:4000
  maxConns                100
  pcKeepAliveTimeout      60
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

phpIniOverride  {
php_admin_value open_basedir "/tmp:$VH_ROOT"
}

module cache {
 storagePath /usr/local/lsws/cachedata/$VH_NAME
}

rewrite  {
 enable                  1
  autoLoadHtaccess        1
}

context /.well-known/acme-challenge {
  location                /usr/local/lsws/Example/html/.well-known/acme-challenge
  allowBrowse             1

  rewrite  {
     enable                  0
  }
  addDefaultCharset       off

  phpIniOverride  {

  }
}


context /api/ {
  type                    proxy
  handler                 dtf-backend
  addDefaultCharset       off
}

context exact:/ {
  location                $DOC_ROOT/index.html
  allowBrowse             1
  extraHeaders            <<<END_extraHeaders
Cache-Control no-cache, no-store, must-revalidate
END_extraHeaders
}

context /index.html {
  location                $DOC_ROOT/index.html
  allowBrowse             1
  extraHeaders            <<<END_extraHeaders
Cache-Control no-cache, no-store, must-revalidate
END_extraHeaders
}

vhssl  {
  keyFile                 /etc/letsencrypt/live/dtf.ninesys19.com/privkey.pem
  certFile                /etc/letsencrypt/live/dtf.ninesys19.com/fullchain.pem
  certChain               1
  sslProtocol             24
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
  enableStapling           1
  ocspRespMaxAge           86400
}
